// GENERATED by sdk/build.py from openapi.json v1.5.8 — do not edit by hand.

package mindupload

import "context"

// CreateCloneParams holds the parameters for CreateClone.
type CreateCloneParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password                         string `json:"password,omitempty"`
	Codename                         string `json:"codename,omitempty"`
	Nickname                         string `json:"nickname,omitempty"`
	Gender                           string `json:"gender,omitempty"`
	AvatarID                         string `json:"avatar_id,omitempty"`
	AcceptChatroomInvitationByOthers *bool  `json:"accept_chatroom_invitation_by_others,omitempty"`
}

// GetClonesParams holds the parameters for GetClones.
type GetClonesParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
}

// UpdateCloneParams holds the parameters for UpdateClone.
type UpdateCloneParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password                         string `json:"password,omitempty"`
	Codename                         string `json:"codename,omitempty"`
	Nickname                         string `json:"nickname,omitempty"`
	Gender                           string `json:"gender,omitempty"`
	AvatarID                         string `json:"avatar_id,omitempty"`
	AcceptChatroomInvitationByOthers *bool  `json:"accept_chatroom_invitation_by_others,omitempty"`
}

// GetQuotaParams holds the parameters for GetQuota.
type GetQuotaParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
}

// CheckUsernameParams holds the parameters for CheckUsername.
type CheckUsernameParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
}

// LoginParams holds the parameters for Login.
type LoginParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
}

// LogoutParams holds the parameters for Logout.
type LogoutParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
}

// RegisterParams holds the parameters for Register.
type RegisterParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password                         string `json:"password,omitempty"`
	Email                            string `json:"email,omitempty"`
	EmailVerificationCode            string `json:"email_verification_code,omitempty"`
	FirstName                        string `json:"first_name,omitempty"`
	LastName                         string `json:"last_name,omitempty"`
	Nickname                         string `json:"nickname,omitempty"`
	Gender                           string `json:"gender,omitempty"`
	BirthDate                        *int64 `json:"birth_date,omitempty"`
	PhoneNumber                      string `json:"phone_number,omitempty"`
	AvatarID                         string `json:"avatar_id,omitempty"`
	AcceptChatroomInvitationByOthers *bool  `json:"accept_chatroom_invitation_by_others,omitempty"`
}

// CheckChatroomUpdatesParams holds the parameters for CheckChatroomUpdates.
type CheckChatroomUpdatesParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// Chatrooms Rooms to check. Each entry must include `chatroom_id`; include `known_updated_at` from the previous response, or null/omit it on the first poll.
	Chatrooms []map[string]any `json:"chatrooms,omitempty"`
}

// CreateChatroomParams holds the parameters for CreateChatroom.
type CreateChatroomParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password             string `json:"password,omitempty"`
	ChatroomName         string `json:"chatroom_name,omitempty"`
	IsPublic             *bool  `json:"is_public,omitempty"`
	AvatarID             string `json:"avatar_id,omitempty"`
	SoulmateCheckEnabled *bool  `json:"soulmate_check_enabled,omitempty"`
}

// CreateChatroomMembershipParams holds the parameters for CreateChatroomMembership.
type CreateChatroomMembershipParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID      string `json:"chatroom_id,omitempty"`
	InviteeUsername string `json:"invitee_username,omitempty"`
	InviteeCodename string `json:"invitee_codename,omitempty"`
	AdminLevel      string `json:"admin_level,omitempty"`
}

// CreateChatroomMessageParams holds the parameters for CreateChatroomMessage.
type CreateChatroomMessageParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
	Text       string `json:"text,omitempty"`
}

// GetChatroomMembershipParams holds the parameters for GetChatroomMembership.
type GetChatroomMembershipParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage   string `json:"preferred_language,omitempty"`
	Page                *int64 `json:"page,omitempty"`
	PageSize            *int64 `json:"page_size,omitempty"`
	SortBy              string `json:"sort_by,omitempty"`
	SortOrder           *int64 `json:"sort_order,omitempty"`
	UseCursorPagination *bool  `json:"use_cursor_pagination,omitempty"`
	CursorValue         string `json:"cursor_value,omitempty"`
	CursorID            string `json:"cursor_id,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
}

// GetChatroomMessagesParams holds the parameters for GetChatroomMessages.
type GetChatroomMessagesParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage   string `json:"preferred_language,omitempty"`
	Page                *int64 `json:"page,omitempty"`
	PageSize            *int64 `json:"page_size,omitempty"`
	SortBy              string `json:"sort_by,omitempty"`
	SortOrder           *int64 `json:"sort_order,omitempty"`
	UseCursorPagination *bool  `json:"use_cursor_pagination,omitempty"`
	CursorValue         string `json:"cursor_value,omitempty"`
	CursorID            string `json:"cursor_id,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string   `json:"chatroom_id,omitempty"`
	SinceValue *float64 `json:"since_value,omitempty"`
	SinceID    string   `json:"since_id,omitempty"`
}

// GetChatroomsParams holds the parameters for GetChatrooms.
type GetChatroomsParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage   string `json:"preferred_language,omitempty"`
	Page                *int64 `json:"page,omitempty"`
	PageSize            *int64 `json:"page_size,omitempty"`
	SortBy              string `json:"sort_by,omitempty"`
	SortOrder           *int64 `json:"sort_order,omitempty"`
	UseCursorPagination *bool  `json:"use_cursor_pagination,omitempty"`
	CursorValue         string `json:"cursor_value,omitempty"`
	CursorID            string `json:"cursor_id,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password   string `json:"password,omitempty"`
	GetPublic  *bool  `json:"get_public,omitempty"`
	GetPrivate *bool  `json:"get_private,omitempty"`
}

// TranslateChatroomMessageParams holds the parameters for TranslateChatroomMessage.
type TranslateChatroomMessageParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
	// MessageID Chatroom message id.
	MessageID string `json:"message_id,omitempty"`
}

// GetChatParams holds the parameters for GetChat.
type GetChatParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage   string `json:"preferred_language,omitempty"`
	Page                *int64 `json:"page,omitempty"`
	PageSize            *int64 `json:"page_size,omitempty"`
	SortBy              string `json:"sort_by,omitempty"`
	SortOrder           *int64 `json:"sort_order,omitempty"`
	UseCursorPagination *bool  `json:"use_cursor_pagination,omitempty"`
	CursorValue         string `json:"cursor_value,omitempty"`
	CursorID            string `json:"cursor_id,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	Codename string `json:"codename,omitempty"`
}

// RagParams holds the parameters for Rag.
type RagParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	Codename string `json:"codename,omitempty"`
	Text     string `json:"text,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
}

// TriggerSocialParams holds the parameters for TriggerSocial.
type TriggerSocialParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password     string `json:"password,omitempty"`
	MembershipID string `json:"membership_id,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
}

// GetMindClusterParams holds the parameters for GetMindCluster.
type GetMindClusterParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password      string `json:"password,omitempty"`
	Codename      string `json:"codename,omitempty"`
	NodeID        string `json:"node_id,omitempty"`
	TextsOffset   *int64 `json:"texts_offset,omitempty"`
	TextsPageSize *int64 `json:"texts_page_size,omitempty"`
	ForceRebuild  *bool  `json:"force_rebuild,omitempty"`
}

// GetSoulmateReportParams holds the parameters for GetSoulmateReport.
type GetSoulmateReportParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password     string `json:"password,omitempty"`
	MyCloneID    string `json:"my_clone_id,omitempty"`
	OtherCloneID string `json:"other_clone_id,omitempty"`
	// ChatroomID Chatroom id as returned by chatroom operations.
	ChatroomID string `json:"chatroom_id,omitempty"`
}

// AbortMultipartUploadParams holds the parameters for AbortMultipartUpload.
type AbortMultipartUploadParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
	// UploadID Multipart upload session id returned by `request_multipart_upload`.
	UploadID string `json:"upload_id,omitempty"`
}

// CancelUploadParams holds the parameters for CancelUpload.
type CancelUploadParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
}

// CompleteMultipartUploadParams holds the parameters for CompleteMultipartUpload.
type CompleteMultipartUploadParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
	// UploadID Multipart upload session id returned by `request_multipart_upload`.
	UploadID string `json:"upload_id,omitempty"`
	// Parts The successfully uploaded parts, using the `part_number` and `etag` returned by each part upload.
	Parts []map[string]any `json:"parts,omitempty"`
}

// ListUploadPartsParams holds the parameters for ListUploadParts.
type ListUploadPartsParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
	// UploadID Multipart upload session id returned by `request_multipart_upload`.
	UploadID string `json:"upload_id,omitempty"`
}

// RequestMultipartUploadParams holds the parameters for RequestMultipartUpload.
type RequestMultipartUploadParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password      string `json:"password,omitempty"`
	Filename      string `json:"filename,omitempty"`
	ContentType   string `json:"content_type,omitempty"`
	FileSizeBytes *int64 `json:"file_size_bytes,omitempty"`
	MediaType     string `json:"media_type,omitempty"`
	HasThumbnail  *bool  `json:"has_thumbnail,omitempty"`
}

// RequestUploadURLParams holds the parameters for RequestUploadURL.
type RequestUploadURLParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password      string `json:"password,omitempty"`
	Filename      string `json:"filename,omitempty"`
	ContentType   string `json:"content_type,omitempty"`
	FileSizeBytes *int64 `json:"file_size_bytes,omitempty"`
	MediaType     string `json:"media_type,omitempty"`
	HasThumbnail  *bool  `json:"has_thumbnail,omitempty"`
}

// SignUploadPartParams holds the parameters for SignUploadPart.
type SignUploadPartParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
	// UploadID Multipart upload session id returned by `request_multipart_upload`.
	UploadID string `json:"upload_id,omitempty"`
	// PartNumber One-based multipart part number.
	PartNumber *int64 `json:"part_number,omitempty"`
}

// SignUploadPartsBatchParams holds the parameters for SignUploadPartsBatch.
type SignUploadPartsBatchParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	// R2Key Opaque media object key returned by upload-start operations and reused for multipart upload calls.
	R2Key string `json:"r2_key,omitempty"`
	// UploadID Multipart upload session id returned by `request_multipart_upload`.
	UploadID string `json:"upload_id,omitempty"`
	// PartNumbers One-based multipart part numbers to sign in a single batch.
	PartNumbers []int64 `json:"part_numbers,omitempty"`
}

// CreateTextParams holds the parameters for CreateText.
type CreateTextParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	Codename string `json:"codename,omitempty"`
	CloneID  string `json:"clone_id,omitempty"`
	Text     string `json:"text,omitempty"`
	Type     string `json:"type,omitempty"`
}

// GetTextsParams holds the parameters for GetTexts.
type GetTextsParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage   string `json:"preferred_language,omitempty"`
	Page                *int64 `json:"page,omitempty"`
	PageSize            *int64 `json:"page_size,omitempty"`
	SortBy              string `json:"sort_by,omitempty"`
	SortOrder           *int64 `json:"sort_order,omitempty"`
	UseCursorPagination *bool  `json:"use_cursor_pagination,omitempty"`
	CursorValue         string `json:"cursor_value,omitempty"`
	CursorID            string `json:"cursor_id,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
	Codename string `json:"codename,omitempty"`
	Type     string `json:"type,omitempty"`
}

// GetUserParams holds the parameters for GetUser.
type GetUserParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password string `json:"password,omitempty"`
}

// UpdateUserParams holds the parameters for UpdateUser.
type UpdateUserParams struct {
	// PreferredLanguage BCP-47-ish language code (e.g. 'en', 'zh-cn') for localized messages.
	PreferredLanguage string `json:"preferred_language,omitempty"`
	// Username The end-user's username.
	Username string `json:"username,omitempty"`
	// Password The end-user's password on first sign-in. After login/register, send the returned session token (JWT) here instead — the field accepts either, and reusing the token keeps raw passwords out of your storage.
	Password                         string `json:"password,omitempty"`
	Email                            string `json:"email,omitempty"`
	EmailVerificationCode            string `json:"email_verification_code,omitempty"`
	FirstName                        string `json:"first_name,omitempty"`
	LastName                         string `json:"last_name,omitempty"`
	Nickname                         string `json:"nickname,omitempty"`
	Gender                           string `json:"gender,omitempty"`
	BirthDate                        *int64 `json:"birth_date,omitempty"`
	PhoneNumber                      string `json:"phone_number,omitempty"`
	AvatarID                         string `json:"avatar_id,omitempty"`
	AcceptChatroomInvitationByOthers *bool  `json:"accept_chatroom_invitation_by_others,omitempty"`
}

// --- AI Consciousnesses ---
// CreateClone Create a new AI consciousness for the user.
//
// Response fields: success, error_message.
// See https://docs.mindupload.app
func (c *Client) CreateClone(ctx context.Context, params CreateCloneParams) (*Response, error) {
	return c.do(ctx, "create_clone", structToMap(params))
}

// GetClones List the user's AI consciousnesses.
//
// Response fields: success, error_message, clones.
// See https://docs.mindupload.app
func (c *Client) GetClones(ctx context.Context, params GetClonesParams) (*Response, error) {
	return c.do(ctx, "get_clones", structToMap(params))
}

// UpdateClone Update an AI consciousness's profile.
//
// Response fields: success, error_message.
// See https://docs.mindupload.app
func (c *Client) UpdateClone(ctx context.Context, params UpdateCloneParams) (*Response, error) {
	return c.do(ctx, "update_clone", structToMap(params))
}

// --- Account ---
// GetQuota Check your partner API rate limits, credit caps, and current usage.
//
// Response fields: success, error_message, per_user_rate_limit_per_min, per_user_daily_credit_cap, partner_rate_limit_per_min, partner_daily_credit_cap, max_users, registered_users, partner_requests_last_minute, partner_credit_spends_last_day, user, user_requests_last_minute, user_credit_spends_last_day, credit_spending_tasks, operation_duration_ms.
// See https://docs.mindupload.app
func (c *Client) GetQuota(ctx context.Context, params GetQuotaParams) (*Response, error) {
	return c.do(ctx, "get_quota", structToMap(params))
}

// --- Authentication ---
// CheckUsername Check whether a username is still available before registering.
//
// Response fields: success, error_message, exists, disabled, rate_limited, flood_window, wait_seconds, operation_duration_ms.
// See https://docs.mindupload.app
func (c *Client) CheckUsername(ctx context.Context, params CheckUsernameParams) (*Response, error) {
	return c.do(ctx, "check_username", structToMap(params))
}

// Login Sign a user in and receive a session token (JWT) for subsequent calls.
//
// Response fields: success, error_message, jwt, decrypted_user.
// See https://docs.mindupload.app
func (c *Client) Login(ctx context.Context, params LoginParams) (*Response, error) {
	return c.do(ctx, "login", structToMap(params))
}

// Logout End the current user session.
//
// Response fields: success, error_message, revoked, operation_duration_ms.
// See https://docs.mindupload.app
func (c *Client) Logout(ctx context.Context, params LogoutParams) (*Response, error) {
	return c.do(ctx, "logout", structToMap(params))
}

// Register Create a user account on your platform.
//
// Response fields: success, error_message, jwt, decrypted_user.
// See https://docs.mindupload.app
func (c *Client) Register(ctx context.Context, params RegisterParams) (*Response, error) {
	return c.do(ctx, "register", structToMap(params))
}

// --- Chatrooms ---
// CheckChatroomUpdates Cheaply poll whether the user's chatrooms have new activity.
//
// Response fields: success, error_message, server_time, poll_config, chatrooms.
// See https://docs.mindupload.app
func (c *Client) CheckChatroomUpdates(ctx context.Context, params CheckChatroomUpdatesParams) (*Response, error) {
	return c.do(ctx, "check_chatroom_updates", structToMap(params))
}

// CreateChatroom Create a chatroom.
//
// Response fields: success, error_message, chatroom_id.
// See https://docs.mindupload.app
func (c *Client) CreateChatroom(ctx context.Context, params CreateChatroomParams) (*Response, error) {
	return c.do(ctx, "create_chatroom", structToMap(params))
}

// CreateChatroomMembership Invite a user or an AI consciousness into a chatroom.
//
// Response fields: success, error_message, membership_id.
// See https://docs.mindupload.app
func (c *Client) CreateChatroomMembership(ctx context.Context, params CreateChatroomMembershipParams) (*Response, error) {
	return c.do(ctx, "create_chatroom_membership", structToMap(params))
}

// CreateChatroomMessage Send a message to a chatroom.
//
// Response fields: success, error_message, message_id.
// See https://docs.mindupload.app
func (c *Client) CreateChatroomMessage(ctx context.Context, params CreateChatroomMessageParams) (*Response, error) {
	return c.do(ctx, "create_chatroom_message", structToMap(params))
}

// GetChatroomMembership List the members of a chatroom the user belongs to.
//
// Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, memberships.
// See https://docs.mindupload.app
func (c *Client) GetChatroomMembership(ctx context.Context, params GetChatroomMembershipParams) (*Response, error) {
	return c.do(ctx, "get_chatroom_membership", structToMap(params))
}

// GetChatroomMessages Fetch messages from a chatroom the user belongs to.
//
// Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, messages, media_thumbnails, since_overflow.
// See https://docs.mindupload.app
func (c *Client) GetChatroomMessages(ctx context.Context, params GetChatroomMessagesParams) (*Response, error) {
	return c.do(ctx, "get_chatroom_messages", structToMap(params))
}

// GetChatrooms List the chatrooms the user belongs to.
//
// Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chatrooms.
// See https://docs.mindupload.app
func (c *Client) GetChatrooms(ctx context.Context, params GetChatroomsParams) (*Response, error) {
	return c.do(ctx, "get_chatrooms", structToMap(params))
}

// TranslateChatroomMessage Translate a text chatroom message into the viewer language.
//
// Response fields: success, error_message, translated_text, target_language, cached.
// See https://docs.mindupload.app
func (c *Client) TranslateChatroomMessage(ctx context.Context, params TranslateChatroomMessageParams) (*Response, error) {
	return c.do(ctx, "translate_chatroom_message", structToMap(params))
}

// --- Conversation ---
// GetChat Fetch the one-on-one conversation history with an AI consciousness.
//
// Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, chats, media_thumbnails.
// See https://docs.mindupload.app
func (c *Client) GetChat(ctx context.Context, params GetChatParams) (*Response, error) {
	return c.do(ctx, "get_chat", structToMap(params))
}

// Rag Send a message to an AI consciousness and receive its reply.
//
// Response fields: success, error_message, response_text, clone_nickname, consolidation_summary, consolidation_count, consolidation_dispatched.
// See https://docs.mindupload.app
func (c *Client) Rag(ctx context.Context, params RagParams) (*Response, error) {
	return c.do(ctx, "rag", structToMap(params))
}

// TriggerSocial Have an AI consciousness proactively join the conversation in a chatroom.
//
// Response fields: success, error_message, response_text, chatroom_digests_count, chatroom_digests_summary, consolidation_summary, consolidation_count, consolidation_dispatched.
// See https://docs.mindupload.app
func (c *Client) TriggerSocial(ctx context.Context, params TriggerSocialParams) (*Response, error) {
	return c.do(ctx, "trigger_social", structToMap(params))
}

// --- Insights ---
// GetMindCluster Fetch the mind-graph visualization data of an AI consciousness.
//
// Response fields: success, error_message, root_node_id, node, children, texts, total_texts, texts_offset, has_more_texts, is_building.
// See https://docs.mindupload.app
func (c *Client) GetMindCluster(ctx context.Context, params GetMindClusterParams) (*Response, error) {
	return c.do(ctx, "get_mind_cluster", structToMap(params))
}

// GetSoulmateReport Generate or fetch the compatibility report between two chatroom members.
//
// Response fields: success, error_message, report, report_generated_at, is_generating, charged.
// See https://docs.mindupload.app
func (c *Client) GetSoulmateReport(ctx context.Context, params GetSoulmateReportParams) (*Response, error) {
	return c.do(ctx, "get_soulmate_report", structToMap(params))
}

// --- Media ---
// AbortMultipartUpload Cancel a multipart upload and discard its parts.
//
// Response fields: success, error_message.
// See https://docs.mindupload.app
func (c *Client) AbortMultipartUpload(ctx context.Context, params AbortMultipartUploadParams) (*Response, error) {
	return c.do(ctx, "abort_multipart_upload", structToMap(params))
}

// CancelUpload Cancel a pending upload.
//
// Response fields: success, error_message.
// See https://docs.mindupload.app
func (c *Client) CancelUpload(ctx context.Context, params CancelUploadParams) (*Response, error) {
	return c.do(ctx, "cancel_upload", structToMap(params))
}

// CompleteMultipartUpload Finish a multipart upload.
//
// Response fields: success, error_message, media_url.
// See https://docs.mindupload.app
func (c *Client) CompleteMultipartUpload(ctx context.Context, params CompleteMultipartUploadParams) (*Response, error) {
	return c.do(ctx, "complete_multipart_upload", structToMap(params))
}

// ListUploadParts List the parts already uploaded in a multipart upload.
//
// Response fields: success, error_message, parts.
// See https://docs.mindupload.app
func (c *Client) ListUploadParts(ctx context.Context, params ListUploadPartsParams) (*Response, error) {
	return c.do(ctx, "list_upload_parts", structToMap(params))
}

// RequestMultipartUpload Start a large-file upload in multiple parts.
//
// Response fields: success, error_message, upload_id, r2_key, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.
// See https://docs.mindupload.app
func (c *Client) RequestMultipartUpload(ctx context.Context, params RequestMultipartUploadParams) (*Response, error) {
	return c.do(ctx, "request_multipart_upload", structToMap(params))
}

// RequestUploadURL Request an upload slot and a signed viewing link for a media attachment.
//
// Response fields: success, error_message, r2_key, presigned_url, media_url, signed_media_url, thumbnail_r2_key, thumbnail_presigned_url, signed_thumbnail_url.
// See https://docs.mindupload.app
func (c *Client) RequestUploadURL(ctx context.Context, params RequestUploadURLParams) (*Response, error) {
	return c.do(ctx, "request_upload_url", structToMap(params))
}

// SignUploadPart Get the signed link for one part of a multipart upload.
//
// Response fields: success, error_message, presigned_url.
// See https://docs.mindupload.app
func (c *Client) SignUploadPart(ctx context.Context, params SignUploadPartParams) (*Response, error) {
	return c.do(ctx, "sign_upload_part", structToMap(params))
}

// SignUploadPartsBatch Get signed links for several parts of a multipart upload at once.
//
// Response fields: success, error_message, presigned_urls.
// See https://docs.mindupload.app
func (c *Client) SignUploadPartsBatch(ctx context.Context, params SignUploadPartsBatchParams) (*Response, error) {
	return c.do(ctx, "sign_upload_parts_batch", structToMap(params))
}

// --- Memories ---
// CreateText Upload a memory or persona entry to an AI consciousness.
//
// Response fields: success, error_message, cluster_label, cluster_modified_count.
// See https://docs.mindupload.app
func (c *Client) CreateText(ctx context.Context, params CreateTextParams) (*Response, error) {
	return c.do(ctx, "create_text", structToMap(params))
}

// GetTexts List the memories and persona entries uploaded to an AI consciousness.
//
// Response fields: success, error_message, total_count, page, page_size, total_pages, has_next, has_prev, next_cursor_value, next_cursor_id, texts.
// See https://docs.mindupload.app
func (c *Client) GetTexts(ctx context.Context, params GetTextsParams) (*Response, error) {
	return c.do(ctx, "get_texts", structToMap(params))
}

// --- Users ---
// GetUser Fetch the signed-in user's profile.
//
// Response fields: success, error_message, jwt, decrypted_user.
// See https://docs.mindupload.app
func (c *Client) GetUser(ctx context.Context, params GetUserParams) (*Response, error) {
	return c.do(ctx, "get_user", structToMap(params))
}

// UpdateUser Update the signed-in user's profile.
//
// Response fields: success, error_message.
// See https://docs.mindupload.app
func (c *Client) UpdateUser(ctx context.Context, params UpdateUserParams) (*Response, error) {
	return c.do(ctx, "update_user", structToMap(params))
}
